package net.infosyscap.focusField.moods.single;

import net.infosyscap.focusField.moods.modal.*;
import net.infosyscap.focusField.moods.sections.breathing.BreathingPhasesResponse;
import net.infosyscap.focusField.moods.sections.breathing.BreathingResponse;
import net.infosyscap.focusField.moods.sections.coach.CoachAnswerResponse;
import net.infosyscap.focusField.moods.sections.coach.CoachResponse;
import net.infosyscap.focusField.moods.sections.coach.CoachStep;
import net.infosyscap.focusField.moods.sections.coach.CoachStepResponse;
import net.infosyscap.focusField.moods.sections.cta.CtaResponse;
import net.infosyscap.focusField.moods.sections.environment.EnvironmentResponse;
import net.infosyscap.focusField.moods.sections.journal.JournalGoalResponse;
import net.infosyscap.focusField.moods.sections.journal.JournalResponse;
import net.infosyscap.focusField.moods.sections.music.MusicResponse;
import net.infosyscap.focusField.moods.sections.relaxbody.RelaxBodyResponse;
import net.infosyscap.focusField.moods.sections.relaxbody.RelaxExerciseResponse;
import net.infosyscap.focusField.moods.sections.spiritual.SpiritualResponse;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class MoodMapper {

    public static MoodResponse toResponse(Mood mood) {
        return MoodResponse.builder()
                .id(mood.getId())
                .slug(mood.getSlug())
                .lang(mood.getLang())
                .name(mood.getName())
                .description(mood.getDescription())
                .imagine(mood.getImagine())
                .helpYou(mood.getHelpYou())
                .music(MusicResponse.builder()
                        .id(mood.getMusic().getId())
                        .title(mood.getMusic().getTitle())
                        .playlistUrl(mood.getMusic().getPlaylistUrl())
                        .tags(mood.getMusic().getTags())
                        .scope(mood.getMusic().getScope())
                        .audius(mood.getMusic().getAudius())
                        .build())
                .breathing(BreathingResponse.builder()
                        .id(mood.getBreathing().getId())
                        .enabled(mood.getBreathing().getEnabled())
                        .techniqueLabel(mood.getBreathing().getTechniqueLabel())
                        .technique(mood.getBreathing().getTechnique())
                        .rounds(mood.getBreathing().getRounds())
                        .totalDurationLabel(mood.getBreathing().getTotalDurationLabel())
                        .totalDuration(mood.getBreathing().getTotalDuration())
                        .scope(mood.getBreathing().getScope())
                        .start(mood.getBreathing().getStart())
                        .stop(mood.getBreathing().getStop())
                        .phases(mood.getBreathing().getPhases().stream()
                                .map(phase -> BreathingPhasesResponse.builder()
                                        .id(phase.getId())
                                        .phase(phase.getPhase())
                                        .phaseLabel(phase.getPhaseLabel())
                                        .duration(phase.getDuration())
                                        .mode(phase.getMode())
                                        .build())
                                .collect(Collectors.toList()))
                        .build())
                .relaxBody(RelaxBodyResponse.builder()
                        .id(mood.getRelaxBody().getId())
                        .enabled(mood.getRelaxBody().getEnabled())
                        .title(mood.getRelaxBody().getTitle())
                        .description(mood.getRelaxBody().getDescription())
                        .start(mood.getRelaxBody().getStart())
                        .stop(mood.getRelaxBody().getStop())
                        .pause(mood.getRelaxBody().getPause())
                        .pauseText(mood.getRelaxBody().getPauseText())
                        .duration(mood.getRelaxBody().getDuration())
                        .scrollDown(mood.getRelaxBody().getScrollDown())
                        .scrollUp(mood.getRelaxBody().getScrollUp())
                        .completed(mood.getRelaxBody().getCompleted())
                        .repeatIn(mood.getRelaxBody().getRepeatIn())
                        .pauseDuration(mood.getRelaxBody().getPauseDuration())
                        .exercises(mood.getRelaxBody().getExercises().stream().map(ex -> RelaxExerciseResponse.builder()
                                .id(ex.getId())
                                .name(ex.getName())
                                .instructions(ex.getInstructions())
                                .duration(ex.getDuration())
                                .image(ex.getImage())
                                .build()).collect(Collectors.toList()))
                        .build())
                .journalPre(JournalResponse.builder()
                        .id(mood.getJournalPre().getId())
                        .enabled(mood.getJournalPre().getEnabled())
                        .prompt(mood.getJournalPre().getPrompt())
                        .placeholder(mood.getJournalPre().getPlaceholder())
                        .save(mood.getJournalPre().getSave())
                        .optional(mood.getJournalPre().getOptional())
                        .build())
                .journalPost(JournalResponse.builder()
                        .id(mood.getJournalPost().getId())
                        .enabled(mood.getJournalPost().getEnabled())
                        .prompt(mood.getJournalPost().getPrompt())
                        .placeholder(mood.getJournalPost().getPlaceholder())
                        .save(mood.getJournalPost().getSave())
                        .optional(mood.getJournalPost().getOptional())
                        .build())
                .journalGoals(
                        mood.getJournalGoals() != null
                                ? JournalResponse.builder()
                                .id(mood.getJournalGoals().getId())
                                .enabled(mood.getJournalGoals().getEnabled())
                                .prompt(mood.getJournalGoals().getPrompt())
                                .placeholder(mood.getJournalGoals().getPlaceholder())
                                .save(mood.getJournalGoals().getSave())
                                .optional(mood.getJournalGoals().getOptional())
                                .goalLabel(mood.getJournalGoals().getGoalLabel())
                                .goals(
                                        mood.getJournalGoals().getGoals() != null
                                                ? mood.getJournalGoals().getGoals().stream()
                                                .map(goal -> JournalGoalResponse.builder()
                                                        .goal(goal.getGoal())
                                                        .how(goal.getHow())
                                                        .build())
                                                .toList()
                                                : List.of()
                                )
                                .build()
                                : null
                )

                .spiritual(SpiritualResponse.builder()
                        .id(mood.getSpiritual().getId())
                        .enabled(mood.getSpiritual().getEnabled())
                        .type(mood.getSpiritual().getType())
                        .verse(mood.getSpiritual().getVerse())
                        .text(mood.getSpiritual().getText())
                        .build())
                .environment(EnvironmentResponse.builder()
                        .id(mood.getEnvironment().getId())
                        .enabled(mood.getEnvironment().getEnabled())
                        .backgroundImage(mood.getEnvironment().getBackgroundImage())
                        .backgroundVideo(mood.getEnvironment().getBackgroundVideo())
                        .soundscape(mood.getEnvironment().getSoundscape())
                        .audioSrc(mood.getEnvironment().getAudioSrc())
                        .suggestion(mood.getEnvironment().getSuggestion())
                        .duration(mood.getEnvironment().getDuration())
                        .title(mood.getEnvironment().getTitle())
                        .start(mood.getEnvironment().getStart())
                        .stop(mood.getEnvironment().getStop())
                        .mute(mood.getEnvironment().getMute())
                        .unmute(mood.getEnvironment().getUnmute())
                        .fullscreen(mood.getEnvironment().getFullscreen())
                        .exitFullscreen(mood.getEnvironment().getExitFullscreen())
                        .suggestedDuration(mood.getEnvironment().getSuggestedDuration())
                        .build())
                .coach(CoachResponse.builder()
                        .id(mood.getCoach().getId())
                        .enabled(mood.getCoach().getEnabled())
                        .intro(mood.getCoach().getIntro())
                        .obstacle(mood.getCoach().getObstacle())
                        .situation(mood.getCoach().getSituation())
                        .feedback(mood.getCoach().getFeedback())
                        .next(mood.getCoach().getNext())
                        .finished(mood.getCoach().getFinished())
                        .noSteps(mood.getCoach().getNoSteps())
                        .steps(mood.getCoach().getSteps().stream().map((CoachStep step) -> CoachStepResponse.builder()
                                .id(step.getId())
                                .situation(step.getSituation())
                                .answers(step.getAnswers().stream().map(ans -> CoachAnswerResponse.builder()
                                        .id(ans.getId())
                                        .text(ans.getText())
                                        .correct(ans.getCorrect())
                                        .feedback(ans.getFeedback())
                                        .build()).collect(Collectors.toList()))
                                .build()).collect(Collectors.toList()))
                        .build())
                .cta(CtaResponse.builder()
                        .id(mood.getCta().getId())
                        .actionCta(mood.getCta().getActionCta())
                        .text(mood.getCta().getText())
                        .build())
                .moodModal(MoodModalResponse.builder()
                        .id(mood.getMoodModal().getId())
                        .loading(mood.getMoodModal().getLoading())
                        .notFound(mood.getMoodModal().getNotFound())
                        .infoModal(InfoModalResponse.builder()
                                .id(mood.getMoodModal().getInfoModal().getId())
                                .title(mood.getMoodModal().getInfoModal().getTitle())
                                .build())
                        .ctaModal(Optional.ofNullable(mood.getMoodModal().getCtaModal())
                                .map(c -> CtaModalResponse.builder()
                                        .id(c.getId())
                                        .defaultText(c.getDefaultText())
                                        .build())
                                .orElse(null))
                        .title(ModalTitleResponse.builder()
                                .id(mood.getMoodModal().getTitle().getId())
                                .calm(mood.getMoodModal().getTitle().getCalm())
                                .build())
                        .desc(ModalDescResponse.builder()
                                .id(mood.getMoodModal().getDesc().getId())
                                .calm(mood.getMoodModal().getDesc().getCalm())
                                .build())
                        .sections(ModalSectionsResponse.builder()
                                .id(mood.getMoodModal().getSections().getId())
                                .music(mood.getMoodModal().getSections().getMusic())
                                .goals(mood.getMoodModal().getSections().getGoals())
                                .journalPre(mood.getMoodModal().getSections().getPreJournal())
                                .breathing(mood.getMoodModal().getSections().getBreathing())
                                .relaxBody(mood.getMoodModal().getSections().getRelaxBody())
                                .coach(mood.getMoodModal().getSections().getCoach())
                                .ambient(mood.getMoodModal().getSections().getAmbient())
                                .spiritual(mood.getMoodModal().getSections().getSpiritual())
                                .journalPost(mood.getMoodModal().getSections().getPostJournal())
                                .build())
                        .build())
                .moodListId(mood.getMoodList().getId())
                .durationSuggestion(mood.getDurationSuggestion())
                .build();
    }
}
